const SPRITE_W = 16;

function norm(rows) {
  return rows.map((r) => (r + '................').slice(0, SPRITE_W));
}

function mirror(rows) {
  return rows.map((r) => [...r].reverse().join(''));
}

const HEAD_BLOCK = [
  '......HHHH......',
  '.....HHHHHH.....',
  '.....HHHHHH.....',
  '.....SSSSSS.....',
  '....SSSSSSSS....',
  '....SsWWSSsS....',
  '...sSSSSSSSSs...',
  '...sSSSSSSSSs...',
];

const HEADS = {
  warrior: norm([
    '.......HH.......',
    '......HHHH......',
    '.....HHHHHH.....',
    '....HHAAAAHH....',
    '....HAAAAAAH....',
    '...HH......HH...',
    '..HHH......HHH..',
    '.HHHH......HHHH.',
  ]),
  wizard: norm([
    '........A.......',
    '.......AAA......',
    '......AAAAA.....',
    '.....AAAAAAA....',
    '..AAAAAAAAAAAAA.',
    '..AA........AA..',
    '................',
    '................',
    '....HHHHHHHH....',
    '...HHHHHHHHHH...',
    '..HHHHHHHHHHHH..',
    '..HHHH..HHHHHH..',
  ]),
  ninja: norm([
    '.....HHHHHH.....',
    '....HHHHHHHH....',
    '...HHHHHHHHHH...',
    '...HHAAAAAAHH...',
    '....HHHHHHHH....',
    '...HHWW..WWHH...',
    '...HHHHHHHHHH...',
    '....HHHHHHHH....',
    '.....AAAAAA.....',
    '..AA..AA...AA...',
  ]),
  priestess: norm([
    '.......HH.......',
    '......HHHH......',
    '.....HHHHHH.....',
    '....HAAAAAAH....',
    '....HHHHHHHH....',
    '..HHH......HHH..',
    '..HHH......HHH..',
    '.HHHH......HHHH.',
    '.HHHH......HHHH.',
    '.HHH........HHH.',
    '.HHH........HHH.',
    '.HHH........HHH.',
    '..HHH......HHH..',
    '................',
  ]),
};

const TORSO = {
  warrior: {
    stand: norm([
      '.KKKKKKKKKKKKKK.',
      'KSSSSSSSSSSSSSSK',
      'KSSssSSSSssSSSSK',
      'KSSssSSSSssSSSSK',
      'KSSSSSSSSSSSSSSK',
      'KSSssssssssSSSSK',
      '.KSSSSSSSSSSSK..',
      '..KMMMMKMMMMK...',
    ]),
    crouch: norm([
      '.KKKKKKKKKKKKK..',
      'KSSSSSSSSSSSSSK.',
      'KSSssSSSSssSSSK.',
      'KSSSSSSSSSSSSSK.',
      '.KMMMMKMMMMK....',
      '..KKKKKKKKKKK...',
    ]),
  },
  wizard: {
    stand: norm([
      '.KKKKKKKKKKKKKK.',
      'KCCCCCCCCCCCCCCK',
      'KCLcCCCCCCcLCCCK',
      'KCLcCCCCCCcLCCCK',
      'KCCCCCCCCCCCCCCK',
      'KCCCCCCCCCCCCCCK',
      '.KCCCCCCCCCCCCK.',
      '..KMMMMKMMMMK...',
    ]),
    crouch: norm([
      '.KKKKKKKKKKKKK..',
      'KCCCCCCCCCCCCSK.',
      'KCLcCCCCCCcLCSK.',
      'KCCCCCCCCCCCCSK.',
      '.KMMMMKMMMMK....',
      '..KKKKKKKKKKK...',
    ]),
  },
  ninja: {
    stand: norm([
      '.KKKKKKKKKKKKKK.',
      'KLLCCCCCCCCCCCLK',
      'KCCcCCCCCCcCCCCK',
      'KCCcCCCCCCcCCCCK',
      'KCCCCCCCCCCCCCCK',
      'KCCCCCCCCCCCCCCK',
      '.KCCCCCCCCCCCCK.',
      '..KMMMMKMMMMK...',
    ]),
    crouch: norm([
      '.KKKKKKKKKKKKK..',
      'KLLCCCCCCCCCCLK.',
      'KCCcCCCCCCcCCCK.',
      'KCCCCCCCCCCCCCK.',
      '.KMMMMKMMMMK....',
      '..KKKKKKKKKKK...',
    ]),
  },
  priestess: {
    stand: norm([
      '..KKKKKKKKKKK...',
      '.KSSSSSSSSSSSK..',
      '.KSSCCCCCCCSSK..',
      '..KCCCCCCCCCK...',
      '..KCCcCCcCCCK...',
      '..KCCcCCcCCCK...',
      '...KKKKKKKKK....',
      '....KMMMMMK.....',
    ]),
    crouch: norm([
      '..KKKKKKKKKKK...',
      '.KSSSSSSSSSSSK..',
      '.KCCCCCCCCCCCK..',
      '..KCCcCCcCCCK...',
      '...KMMMMMK......',
      '....KKKKKK......',
    ]),
  },
};

const LEGS_STAND = norm([
  '...KKKK.KKKK....',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KKKKK.KKKKK...',
  '...KDDD.DDDK....',
  '...KDDD.DDDK....',
  '...KDDD.DDDK....',
  '...KDDD.DDDK....',
  '....KKK.KKK.....',
]);

const LEGS_ATTACK = norm([
  '...KKKK.KKKK....',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KKKKK.KKKKK...',
  '..KDDDD.KDDDK...',
  '..KDDDD..KDDK...',
  '..KDDD...KDDK...',
  '..KKK.....KK....',
  '................',
  '................',
]);

const LEGS_RUN_0 = norm([
  '..KKKKK.KKKK....',
  '.KSSSSS.SSSSK...',
  '.KSSSS..SSSSK...',
  '.KSSS...SSSSK...',
  '.KSS....SSSSK...',
  '.KSS....KKKKK...',
  '.KKK...KDDDD....',
  '......KDDD......',
  '.....KDDD.......',
  '.....KKK........',
  '................',
  '................',
]);

const LEGS_RUN_1 = norm([
  '..KKKKK..KKKKK..',
  '.KSSSSS..SSSSSK.',
  '.KSSSSS..SSSSSK.',
  '.KSSSSS..SSSSSK.',
  '.KSSSSS..SSSSSK.',
  '.KKKKKK..KKKKKK.',
  '..KDDD....DDDK..',
  '..KDDD....DDDK..',
  '..KDDD....DDDK..',
  '...KKK....KKK...',
  '................',
  '................',
]);

const LEGS_JUMP_0 = norm([
  '...KKKK.KKKK....',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KSSSS.SSSSK...',
  '..KKKKK.KKKKK...',
  '...KDDD.DDDK....',
  '...KDDD.DDDK....',
  '...KDDD.DDDK....',
  '...KKKK.KKKK....',
  '................',
  '................',
]);

const LEGS_JUMP_1 = norm([
  '................',
  '...KKKK..KKKK...',
  '..KSSSS..SSSSK..',
  '..KSSSS..SSSSK..',
  '..KSSSS..SSSSK..',
  '..KKKKK..KKKKK..',
  '...KDDD..DDDK...',
  '...KDDD..DDDK...',
  '...KKKK..KKKK...',
  '................',
  '................',
  '................',
]);

const LEGS_JUMP_2 = norm([
  '................',
  '....KKKK.KKKK...',
  '...KSSSS.SSSSK..',
  '...KSSSS.SSSSK..',
  '..KSSSSS.SSSSK..',
  '..KKKKKK.KKKKK..',
  '..KDDDDD.DDDDK..',
  '..KDDDDD.DDDDK..',
  '..KKKKKK.KKKKK..',
  '................',
  '................',
  '................',
]);

const LEGS_LAND = norm([
  '................',
  '..KKKKK..KKKKK..',
  '.KSSSSS..SSSSSK.',
  '.KSSSSS..SSSSSK.',
  '.KSSSSS..SSSSSK.',
  'KKKKKKK..KKKKKKK',
  'KDDDDD....DDDDDK',
  'KDDDDD....DDDDDK',
  'KKKKKK....KKKKKK',
  '................',
  '................',
  '................',
]);

const LEGS_CROUCH = norm([
  '.KKKKK..KKKKK...',
  'KDDDDD..DDDDD...',
  'KDDDDD..DDDDD...',
  'KDDDDD..DDDDD...',
  'KKKKKK..KKKKKK..',
  '................',
]);

const LEGS_CROUCH_WALK_A = norm([
  '..KKKKK..KKKKK..',
  '.KDDDDD...DDDDD.',
  '.KDDDDD...DDDDD.',
  '.KDDDDD....DDDD.',
  '.KKKKK.....KKKK.',
  '................',
]);

const LEGS_CROUCH_WALK_B = norm(mirror(LEGS_CROUCH_WALK_A));

const ACCENTS = {
  warrior: {
    stand: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....CCC.........',
      '.....CCC........',
      '......CCC.......',
      '.......CCC......',
      '........CCC.....',
      '................',
      '................',
      '..CCCCCCCCCCCC..',
      '..CCCCCCCCCCCC..',
      '..cCCCCCCCCCCc..',
      '...cCCCCCCCCc...',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]),
    crouch: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..CCCCCCCCCCCC..',
      '..CCCCCCCCCCCC..',
      '..cCCCCCCCCCCc..',
      '...cCCCCCCCCc...',
      '................',
      '................',
    ]),
  },
  wizard: {
    stand: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '...KCCCCCCCCK...',
      '..KCLccccccCLK..',
      '..KCCCCCCCCCCK..',
      '..KCLcccccccLK..',
      '..KCCCCCCCCCCK..',
      '..KCLcccccccLK..',
      '..KCCCCCCCCCCK..',
      '..KMMMMMMMMMMK..',
      '.KCCCCCCCCCCCCK.',
      '.KCLccccccccccK.',
      'KCCCCCCCCCCCCCCK',
      'KCLccccccccccccK',
      'KCCCCCCCCCCCCCCK',
      'KCLccccccccccccK',
      'KCCCCCCCCCCCCCCK',
      'KCLccccccccccccK',
      'KCCCCCCCCCCCCCCK',
      'KCLccccccccccccK',
      'KCCCCCCCCCCCCCCK',
      '.KKKKKKKKKKKKKK.',
    ]),
    crouch: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..KCCCCCCCCCK...',
      '..KCLccccccLK...',
      '..KCCCCCCCCCK...',
      '..KCLccccccLK...',
      '..KCCCCCCCCCK...',
      '.KMMMMMMMMMMK...',
      '.KCCCCCCCCCCK...',
      'KCCCCCCCCCCCCK..',
      'KCLccccccccccK..',
      'KCCCCCCCCCCCCK..',
      '.KKKKKKKKKKKKK..',
      '................',
    ]),
  },
  ninja: {
    stand: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..KCCCCCCCCCK...',
      '..KCCCCCCCCCK...',
      '..KCCcCCCCcCK...',
      '..KCCCCCCCCCK...',
      '..KCCCCCCCCCK...',
      '..KCCcCCCCcCK...',
      '..KCCCCCCCCCK...',
      '..KCCCCCCCCCK...',
      '..KCCCCCCCCCK...',
      '..KKKKKKKKKKK...',
      '................',
      '................',
    ]),
    crouch: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..KCCCCCCCCCK...',
      '..KCCCCCCCCCK...',
      '..KCCcCCCCcCK...',
      '..KCCCCCCCCCK...',
      '..KKKKKKKKKKK...',
      '................',
    ]),
  },
  priestess: {
    stand: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..KCCCCCCCCCCK..',
      '..KCCCCCCCCCCK..',
      '..KCCcCCCCcCCCK.',
      '..KCCCCCCCCCCK..',
      '..KCCCCCCCCCCK..',
      '..KCCcCCCCcCCCK.',
      '..KCCCCCCCCCCK..',
      '...KCCCCCCCCK...',
      '...KcCCCCCCcK...',
      '................',
      '................',
      '................',
    ]),
    crouch: norm([
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..KCCCCCCCCCCK..',
      '..KCCcCCCCcCCCK.',
      '..KCCCCCCCCCCK..',
      '...KcCCCCCCcK...',
      '................',
      '................',
    ]),
  },
};

const CLASS_PALETTES = {
  warrior: {
    K: '#241008', S: '#e8b07a', s: '#c8935f', W: '#ffffff', H: '#e8b038', h: '#b07e20',
    A: '#f0d24a', a: '#c09a2e', C: '#d04028', c: '#8a2216', L: '#e86a4a', M: '#d8d8e0', m: '#9a9aac', D: '#6a3f20',
  },
  wizard: {
    K: '#18181e', S: '#e8b07a', s: '#c8935f', W: '#ffffff', H: '#d8d8d8', h: '#a8a8a8',
    A: '#b8b8c2', a: '#78788a', C: '#6a6a78', c: '#484854', L: '#9a9aa8', M: '#c8b888', m: '#8a7a52', D: '#3a3a44',
  },
  ninja: {
    K: '#0c0c14', S: '#e8b07a', s: '#c8935f', W: '#ffffff', H: '#1c1c26', h: '#06060c',
    A: '#d84030', a: '#8a1f18', C: '#2e4a8a', c: '#1c3060', L: '#4a6ab8', M: '#d8d8e0', m: '#9a9aac', D: '#12161e',
  },
  priestess: {
    K: '#241016', S: '#f0c090', s: '#d0a070', W: '#ffffff', H: '#c8a050', h: '#a07a30',
    A: '#f5f5f0', a: '#d0d0c8', C: '#e0a8c8', c: '#b07e9c', L: '#f2d0e0', M: '#e8d8a0', m: '#b8a46a', D: '#8a5a3a',
  },
};

function buildPoses(torsoStand, torsoCrouch) {
  const st = (legs) => HEAD_BLOCK.concat(torsoStand, legs);
  const cr = (legs) => HEAD_BLOCK.concat(torsoCrouch, legs);
  return {
    idle: [st(LEGS_STAND), st(LEGS_STAND)],
    run: [
      st(LEGS_RUN_0),
      st(LEGS_RUN_1),
      st(LEGS_RUN_2),
      st(LEGS_RUN_3),
    ],
    jump: [
      st(LEGS_JUMP_0),
      st(LEGS_JUMP_1),
      st(LEGS_JUMP_2),
    ],
    attack: [
      st(LEGS_ATTACK),
      st(LEGS_ATTACK),
      st(LEGS_STAND),
    ],
    land: [st(LEGS_LAND)],
    crouch: [cr(LEGS_CROUCH)],
    crouchWalk: [
      cr(LEGS_CROUCH_WALK_A),
      cr(LEGS_CROUCH_WALK_B),
    ],
  };
}

const LEGS_RUN_2 = norm(mirror(LEGS_RUN_0));
const LEGS_RUN_3 = norm(mirror(LEGS_RUN_1));

const SPRITES = {
  warrior: buildPoses(TORSO.warrior.stand, TORSO.warrior.crouch),
  wizard: buildPoses(TORSO.wizard.stand, TORSO.wizard.crouch),
  ninja: buildPoses(TORSO.ninja.stand, TORSO.ninja.crouch),
  priestess: buildPoses(TORSO.priestess.stand, TORSO.priestess.crouch),
};

const WEAPONS = {
  warrior: {
    dx: 2,
    dy: 2,
    grid: norm([
      '.............KM.',
      '............KMMK',
      '...........KMMK.',
      '..........KMMK..',
      '.........KMMK...',
      '........KMMK....',
      '.......KMMK.....',
      '......KMMK......',
      '.....KMMK.......',
      '....KMMK........',
      '...KMMK.........',
      '..KMMK..........',
      '.KMMK...........',
      'KMMK............',
      'MMK.............',
      'KK..............',
    ]),
  },
  wizard: {
    dx: 2,
    dy: 0,
    grid: norm([
      '.......AA.......',
      '......AAAA......',
      '.......AA.......',
      '......A.A.......',
      '......M.M.......',
      '......M.M.......',
      '.....M...M......',
      '....M.....M.....',
      '...M.......M....',
      '..M.........M...',
      '.M...........M..',
      'M.............M.',
      '..............M.',
      '..............M.',
    ]),
  },
  ninja: {
    dx: 3,
    dy: 3,
    grid: norm([
      '...........KK...',
      '...........KMW..',
      '...........KMM..',
      '..........KMM...',
      '.........KMM....',
      '........KMM.....',
      '.......KMM......',
      '......KMM.......',
      '.....KMM........',
      '....KMM.........',
      '...KMM..........',
      '..KMM...........',
      '.KMM............',
      'KMM.............',
    ]),
  },
  priestess: {
    dx: 6,
    dy: 1,
    grid: norm([
      '......AAAA......',
      '.....AA..AA.....',
      '.....A.AA.A.....',
      '.....AAAAAA.....',
      '.....AA..AA.....',
      '......AAAA......',
      '.......MM.......',
      '.......MM.......',
      '.......MM.......',
      '.......MM.......',
      '.......MM.......',
      '.......MM.......',
      '.......MM.......',
    ]),
  },
};

const ENEMY_A = [
  '.....KKKKKK.....',
  '....KSSSSSSK....',
  '...KSSSSSSSSK...',
  '...KSWWSSWWSK...',
  '...KSSSSSSSSK...',
  '....KSSSSSSK....',
  '....KKKKKKKK....',
  '...KCCCCCCCCK...',
  '..KCCcCCCCcCCK..',
  '..KCCCCCCCCCCK..',
  '..KCCCCCCCCCCK..',
  '..KcCCCCCCCCcK..',
  '..KCCCCCCCCCCK..',
  '...KCCCCCCCCK...',
  '....KKKKKKKK....',
  '....KDD..KDD....',
  '....KDD..KDD....',
  '....KKK..KKK....',
];

const ENEMY_B = [
  '.....KKKKKK.....',
  '....KSSSSSSK....',
  '...KSSSSSSSSK...',
  '...KSWWSSWWSK...',
  '...KSSSSSSSSK...',
  '....KSSSSSSK....',
  '....KKKKKKKK....',
  '...KCCCCCCCCK...',
  '..KCCcCCCCcCCK..',
  '..KCCCCCCCCCCK..',
  '..KCCCCCCCCCCK..',
  '..KcCCCCCCCCcK..',
  '..KCCCCCCCCCCK..',
  '...KCCCCCCCCK...',
  '....KKKKKKKK....',
  '...KDD..KDD.....',
  '...KDD...KDD....',
  '...KKK...KKK....',
];

const ENEMY_SPRITES = [norm(ENEMY_A), norm(ENEMY_B)];

const ENEMY_PALETTE = {
  K: '#12100a',
  S: '#8aa83e',
  s: '#64802a',
  W: '#ffe066',
  C: '#6a4a2a',
  c: '#4a3218',
  D: '#3a2818',
};
