const SPRITE_W = 14;

function norm(rows) {
  return rows.map((r) => (r + '..............').slice(0, SPRITE_W));
}

const IDLE_A = [
  '....HHH.....',
  '...HHHHH....',
  '...HSSSH....',
  '..HSWWSSH...',
  '..HSSSSSH...',
  '...SSSSS....',
  '..CCCCCCC...',
  '.CCCCCCCCC..',
  '.cCCCCCCCc..',
  '.cCCCCCCCc..',
  '.cCCCCCCcC..',
  '..CCCCCCCC..',
  '..CCCCCCCC..',
  '..MMMMMMM...',
  '..CCCCCCCC..',
  '.CCC..CCC...',
  '.CC....CC...',
  '.CC....CC...',
  '.CC....CC...',
  '..S....SS...',
  '..SS...SS...',
  '..SS...SS...',
  '.SS....SS...',
  '.SS....SS...',
  'KK......KK..',
  'KK......KK..',
];

const IDLE_B = [
  '....HHH.....',
  '...HHHHH....',
  '...HSSSH....',
  '..HSWWSSH...',
  '..HSSSSSH...',
  '...SSSSS....',
  '..CCCCCCC...',
  '.CCCCCCCCC..',
  '.cCCCCCCCc..',
  '.cCCCCCCCc..',
  '.cCCCCCCcC..',
  '..CCCCCCCC..',
  '..CCCCCCCC..',
  '..MMMMMMM...',
  '..CCCCCCCC..',
  '.CCC..CCC...',
  '.CC....CC...',
  '.CC....CC...',
  '.CC....CC...',
  '..S....SS...',
  '..SS...SS...',
  '..SS...SS...',
  '..SS...SS...',
  '..SS...SS...',
  '..KK...KK...',
  '..KK...KK...',
];

const RUN_A = [
  '....HHH.....',
  '...HHHHH....',
  '...HSSSH....',
  '..HSWWSSH...',
  '..HSSSSSH...',
  '...SSSSS....',
  '.CCCCCCCC...',
  '.cCCCCCCc...',
  '.cCCCCCCc...',
  '.cCCCCCCc...',
  '..CCCCCCCC..',
  '..CCCCCCCC..',
  '..MMMMMMM...',
  '..CCCCCCCC..',
  '.CC.CCCC....',
  '.CC..C......',
  '.CC.........',
  '.CC.....CC..',
  '.CC.....CC..',
  '..SS...SS...',
  '..SS..SS....',
  '..SSSS......',
  '..SSSS......',
  '.KK.........',
  '.KK.........',
  '............',
];

const RUN_B = [
  '....HHH.....',
  '...HHHHH....',
  '...HSSSH....',
  '..HSWWSSH...',
  '..HSSSSSH...',
  '...SSSSS....',
  '.CCCCCCCC...',
  '.cCCCCCCc...',
  '.cCCCCCCc...',
  '.cCCCCCCc...',
  '..CCCCCCCC..',
  '..CCCCCCCC..',
  '..MMMMMMM...',
  '..CCCCCCCC..',
  '.CC..CCC....',
  '.CC...C.....',
  '.CC.........',
  '.CC.........',
  '.CC.........',
  '..SSSSSS....',
  '..SSSSSS....',
  '..SSSSSS....',
  '..SSSSSS....',
  '..KKKKKK....',
  '..KKKKKK....',
  '............',
];

const RUN_C = [
  '....HHH.....',
  '...HHHHH....',
  '...HSSSH....',
  '..HSWWSSH...',
  '..HSSSSSH...',
  '...SSSSS....',
  '.CCCCCCCC...',
  '.cCCCCCCc...',
  '.cCCCCCCc...',
  '.cCCCCCCc...',
  '..CCCCCCCC..',
  '..CCCCCCCC..',
  '..MMMMMMM...',
  '..CCCCCCCC..',
  '.CCCC.CC....',
  '...C..CC....',
  '......CC....',
  '..CC...CC...',
  '..CC...CC...',
  '..SS...SS...',
  '....SS..SS..',
  '......SSSS..',
  '......SSSS..',
  '..........KK',
  '..........KK',
  '............',
];

const JUMP = [
  '....HHH.....',
  '...HHHHH....',
  '...HSSSH....',
  '..HSWWSSH...',
  '..HSSSSSH...',
  '...SSSSS....',
  '.CCCCCCCCCC.',
  '.cCCCCCCCc..',
  '.cCCCCCCCc..',
  '.CCCCCCCCC..',
  '.CCCCCCCCC..',
  '..CCCCCCCC..',
  '..MMMMMMM...',
  '..CCCCCCCC..',
  '..CCCCCCCC..',
  '.CC....CC...',
  '.SS....SS...',
  '.SS....SS...',
  '.SS....SS...',
  '.SS....SS...',
  '.SS....SS...',
  '..SS..SS....',
  '..SS..SS....',
  '...KKKK.....',
  '............',
  '............',
];

const ATTACK = [
  '....HHH.....',
  '...HHHHH....',
  '...HSSSH....',
  '..HSWWSSH...',
  '..HSSSSSH...',
  '...SSSSS....',
  '..CCCCCCC...',
  '.CCCCCCCCC..',
  '.cCCCCCCCc..',
  '.cCCCCCCCc..',
  '.cCCCCCCcC..',
  '..CCCCCCCC..',
  '..CCCCCCCC..',
  '..MMMMMMM...',
  '..CCCCCCCC..',
  '.CCCCCCCCMM.',
  '.CCCCCCCCMM.',
  '.CC.........',
  '.CC.........',
  '..SS...SS...',
  '..SS...SS...',
  '..SS...SS...',
  '.SS....SS...',
  '.SS....SS...',
  'KK......KK..',
  'KK......KK..',
];

const POSES = {
  idle: [norm(IDLE_A), norm(IDLE_B)],
  run: [norm(RUN_A), norm(RUN_B), norm(RUN_C)],
  jump: [norm(JUMP)],
  attack: [norm(ATTACK)],
};

const WARRIOR_HEAD = [
  '..AAAAAA.....',
  '.AAAAAAAA....',
  'AAAAMMAAAA...',
  'AAAMMMAAMA...',
  '.AAAAAAA.....',
  '..AAAAAA.....',
];

const WIZARD_HEAD = [
  '..AA.........',
  '.AAAAAAAAAA..',
  'AAAAAAAAAAAA.',
  '..AAAAAAAAA..',
  '...AAAAAAA...',
  '....AAAAA....',
  '.....AAA.....',
];

const NINJA_HEAD = [
  '...AAA.......',
  '..AAAAA......',
  '..HAAAAH.....',
  '..HSSSSH.....',
  '..HSWWSH.....',
  '..HSSSSH.....',
  '..KKKKKK.....',
];

const PRIESTESS_HEAD = [
  '.AAAAAAAAAA..',
  '..AAAAAAAA...',
  '..AHSSSSHA...',
  '..AHSWWSHA...',
  '..AHSSSSSA...',
  '...ASSSSS....',
  '....AAAA.....',
];

const HEADS = {
  warrior: norm(WARRIOR_HEAD),
  wizard: norm(WIZARD_HEAD),
  ninja: norm(NINJA_HEAD),
  priestess: norm(PRIESTESS_HEAD),
};

const CLASS_SPRITES = {
  warrior: {
    palette: {
      S: '#e8b07a', s: '#c8935f', C: '#c0392b', c: '#8a2216',
      M: '#c8c8d0', H: '#6b3a1f', h: '#4a2812', W: '#ffffff', A: '#d0d0d8',
    },
    head: HEADS.warrior,
  },
  wizard: {
    palette: {
      S: '#e8b07a', s: '#c8935f', C: '#2e5cc8', c: '#1c3a80',
      M: '#c8c8d0', H: '#c8c8d0', h: '#a8a8b0', W: '#ffffff', A: '#d9a63a',
    },
    head: HEADS.wizard,
  },
  ninja: {
    palette: {
      S: '#e8b07a', s: '#c8935f', C: '#6a2fc0', c: '#461b8a',
      M: '#c8c8d0', H: '#1a1a1a', h: '#000000', W: '#ffffff', A: '#c0392b',
    },
    head: HEADS.ninja,
  },
  priestess: {
    palette: {
      S: '#e8b07a', s: '#c8935f', C: '#d9a63a', c: '#a87b22',
      M: '#c8c8d0', H: '#f0d8a0', h: '#d0b878', W: '#ffffff', A: '#f5f5f0',
    },
    head: HEADS.priestess,
  },
};

const ENEMY_A = [
  '....KKKK.....',
  '...KSSSSK....',
  '..KSSSSSSK...',
  '..KSSWWSSK...',
  '..KSSSSSSK...',
  '...KKKKKK....',
  '..KCCCCCCK...',
  '.KCCCCCCCCK..',
  '.KCCCCCCCCK..',
  '..KCCCCCCK...',
  '..KCCCCCCK...',
  '..KCCCCCCK...',
  '.KcCCCCCCcK..',
  '.KcCCCCCCcK..',
  '..KcCCCCcK...',
  '...KCCCCK....',
  '....KKKK.....',
  '....KK.KK....',
];

const ENEMY_B = [
  '....KKKK.....',
  '...KSSSSK....',
  '..KSSSSSSK...',
  '..KSSWWSSK...',
  '..KSSSSSSK...',
  '...KKKKKK....',
  '..KCCCCCCK...',
  '.KCCCCCCCCK..',
  '.KCCCCCCCCK..',
  '..KCCCCCCK...',
  '..KCCCCCCK...',
  '..KCCCCCCK...',
  '.KcCCCCCCcK..',
  '.KcCCCCCCcK..',
  '..KcCCCCcK...',
  '...KCCCCK....',
  '....KKK.KK...',
  '.....KK.KK...',
];

const ENEMY_SPRITES = [norm(ENEMY_A), norm(ENEMY_B)];

const ENEMY_PALETTE = {
  K: '#0a0a0a',
  S: '#e8b07a',
  C: '#b23b4a',
  c: '#7a2230',
  W: '#ffe066',
};
